#! /bin/sh

polybar example &
redshift &
feh --bg-scale ~/Pictures/SBKjnxm.jpg &
xinput set-prop 13 308 1 &
picom &


pgrep -x sxhkd > /dev/null || sxhkd &








bspc config top_padding 23
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         0
bspc config window_gap           3


bspc config focused_border_color "#3b4252"
bspc config normal_border_color "#3b4252"
bspc config split_ratio          0.50

bspc subscribe node_state | while read -r _ _ _ node state status; do
    if [[ "$state" == "floating" ]]; then
        case "$status" in
            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        esac
    fi
done
