#! /bin/sh

polybar example &
redshift &
feh --bg-scale ~/Pictures/SBK.jpg &

xinput set-prop 13 308 1 &

picom &

flashfocus &

pgrep -x sxhkd > /dev/null || sxhkd &








bspc config top_padding 20
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         0
bspc config window_gap           4

bspc config presel_feedback_color "#3B4252"
bspc config focused_border_color "#A3BE8C"
bspc config normal_border_color "#434C5E"
bspc config split_ratio          0.50


bspc rule -a Zathura state=tiled
##for shadows in compton only in floating mode
#bspc subscribe node_state | while read -r _ _ _ node state status; do
#    if [[ "$state" == "floating" ]]; then
#        case "$status" in
#            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
#            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
#        esac
#    fi
#done
