#! /bin/sh

polybar example &
redshift &
feh --bg-scale ~/Pictures/SBKjnxm.jpg &
xinput set-prop 13 300 1 &
compton &


pgrep -x sxhkd > /dev/null || sxhkd &








bspc config top_padding 23
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

